name: pre-commit

on:
  pull_request:
  push:
    branches-ignore:
      - "main"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gabe565/setup-helm-docs-action@v1
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
